### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by dondledunk** [twn9/Spotify_to_Youtube#1]
Can you add a license granting at least permission to private use for this code? I am totally new to coding, and for practice, I want to make a program, and I think this code could make my life easier. I want to make a program that grabs the file properties (song title/artist/etc.) of a bunch of mp3s on a flash drive, automatically searches for it on youtube, grabs the first result on youtube, and adds it to a playlist. Thanks!

**Comment by twn9** [comment]
Just added a license. GL with your project!
